name: GitHub Metrics 2D
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GH_TOKEN secret you created earlier
          token: ${{ secrets.GH_TOKEN }}

          # Options
          user: ${{ github.repository_owner }}
          template: classic
          base: header, community, repositories, metadata
          config_timezone: UTC
          
          # Visual Settings
          theme: dark
          config_order: base.header, isocalendar, languages, achievements
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          
          # Output Location
          filename: github-metrics.svg
